### PR TITLE
improve hints in bert embedding, fixed output to feature but fine-tun…

### PR DESCRIPTION
**Pull request by alexwwang**
keep consistency of bert embedding in tf.keras version.

### CODE REVIEW

**Comment by BrikerMan** [comment]
I have added flake8 style check for the project, please fix the CI errors~

**Comment by alexwwang** [comment]
> I have added flake8 style check for the project, please fix the CI errors~

Nice, I will right away.
Btw, what does `bert only more 2` mean on line 63?

**Comment by BrikerMan** [comment]
@alexwwang It is legacy code from the first design which allows multi-input for embedding layers. Just change it to some-thing like this.

```
if isinstance(sequence_length, tuple):
    raise ValueError('must be int')
```

**Comment by BrikerMan** [comment]
@alexwwang One more thing, I think it will be cool if we all use the [gitmoji](https://gitmoji.carloscuesta.me), check it out.

**Comment by alexwwang** [comment]
> @alexwwang One more thing, I think it will be cool if we all use the [gitmoji](https://gitmoji.carloscuesta.me), check it out.

Noticed. Next time I'll have a try. 😈

**Pull request merged**
