### PR TITLE
:construction: add AVCNN_Model, KMax_CNN_Model & related customized layers

### PR DESCRIPTION
**Pull request by alexwwang**
4/6

`classification.__init__.py` would be updated when all models finished.

### CODE REVIEW

**Comment by BrikerMan** [comment]
@alexwwang Build failed, check it out.

**Comment by alexwwang** [comment]
Later.

**Comment by BrikerMan** [comment]
@alexwwang I think this might help for issues like 
```
A002 "sorted" is used as an argument and thus shadows a python builtin, consider renaming the argument
```
Check it out, http://flake8.pycqa.org/en/3.1.1/user/ignoring-errors.html#in-line-ignoring-errors

**Comment by alexwwang** [comment]
thanks a lot.
let me have a try.

**Comment by alexwwang** [comment]
it's so awkward. 🤦‍♂️

**Comment by BrikerMan** [comment]
> it's so awkward. 🤦‍♂️

Haha, that's ok, You could install flake8 and run before commit locally.

```bash
pip install flake8 flake8-builtins
flake8 kashgari
```

**Comment by alexwwang** [comment]
I'll do it right now!

**Comment by alexwwang** [comment]
Done! Thank you!

**Pull request merged**
