### PR TITLE
refactor sequence-labeling model

### PR DESCRIPTION
**Pull request by BrikerMan**
* change LSTM layer to LSTMLayer with cuDNN cell support
* refactor Sequence labeling __base_hyper_parameters__

### CODE REVIEW

**Comment by BrikerMan** [comment]
@alexwwang please review this merge~ And remember to check your email, I have added you as a collaborator to Kashgari.

**Comment by alexwwang** [comment]
I plan to change `eval` to `ast.literal_eval` later.
The same to classification part, I think we could use `ast.literal_eval` to get `crf_loss` and `crf_accuracy` instance from string value in `self.hyper_parameters` dict.

One more thing, I've not received notification email about collaborator yet. 
Is there anything wrong?

**Comment by BrikerMan** [comment]
@alexwwang Please give your email, I will send invite directly to your email.

**Comment by alexwwang** [comment]
You may directly add me in the collaborate list by my account name
@alexwwang
Please notice there are double w's in my account name.
https://github.com/alexwwang

**Comment by BrikerMan** [comment]
@alexwwang I have already added you from project setting.
image

**Comment by alexwwang** [comment]
I see. I will check it tomorrow. Maybe there is a possibility I overlooked.

**Comment by alexwwang** [comment]
I find your invitation and accepted. Too many mails rushed at that time and
I just missed it.
It's OK now.👌

**Comment by BrikerMan** [comment]
@alexwwang when you are going to change `eval` to `ast.literal_eval`? I am planning to move code of multi-label classification to this merge request.
If you are already working on the `eval` function change, I will do it later to avoid repeated work and conflict. Otherwise, I am planning to finish the multi-label classification today. Then you could do your part.

**Comment by alexwwang** [comment]
Maybe later today or tomorrow? I am configuring and transferring data to a
new PC now. You may merge first and then I work based on your node.

**Comment by BrikerMan** [comment]
@alexwwang I have finished multi-label classification tokenize and predict function. Remember to help me out with here. https://github.com/BrikerMan/Kashgari/blob/9d1cb5ff1e0c2baeda33a763c0a55b26aea2053c/kashgari/tasks/classification/models.py#L61

Take your time, no rush~

**Comment by alexwwang** [comment]
@BrikerMan Got it. Any answer to the purpose of deletion in `macro.py`? The question I raised above. I've no idea why you do it yet.

**Comment by BrikerMan** [comment]
CustomEmbedding is duplicated with the embeddings.CustomEmbedding. Download function is unused. So I removed them.

**Comment by alexwwang** [comment]
done

**Pull request closed without merging**
