### PR TITLE
WIP: Feature/multi label classification

### PR DESCRIPTION
**Pull request by BrikerMan**

### CODE REVIEW

**Comment by alexwwang** [comment]
You've done most of this work. Combine your data processing part with mine model part, I think it's acceptable by now as a first solution.
Btw, I can't get the idea why add the sentiment process in `corpus.py`. Would you kindly explain it?

**Comment by BrikerMan** [comment]
I think the whole idea of the corpus.py is to provide a pre-processed data-set for the training process. So I added a new class to read my multi-label dataset while I was testing the multi-label classification model.
I am planning to rewrite the corpus.py to make it clean and simple, but have no idea how to do that.

**Comment by alexwwang** [comment]
According to my understanding, `corpus.py` means `corpus_preprocessing.py`, right?
Then I think maybe it's better to develop a toolbox of small utilities aiming at dealing with different tasks in future. Thus users could pick up those they need to assemble freely to deal with their tasks.

**Comment by BrikerMan** [comment]
Yes, that is the plan. We need to provide a small toolbox to pre-process user data. I think we should start with pre-processing tools for well known public dataset first.

**Comment by alexwwang** [comment]
Well, I thought it depends on. Maybe tools to handle part of those public dataset have been already widely developed.
Users are also encouraged to submit their own preprocessing tools here if they find the models here are useful and effective.
This is my idea, to focus on model side. More models support various types of tasks, which would also attract more users with their preprocessing tools.

**Comment by BrikerMan** [comment]
You are right, we should focus on the model side, provide more models to handle various NLP tasks. I have added you as a collaborator. Please add your vision to the https://github.com/BrikerMan/Kashgari/projects/2, then we finish the tasks one by one.

**Pull request closed without merging**
